// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./stories/Button.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    FeatherClock: typeof import('~icons/feather/clock')['default']
    FeatherGithub: typeof import('~icons/feather/github')['default']
    FeatherHome: typeof import('~icons/feather/home')['default']
    FeatherMoon: typeof import('~icons/feather/moon')['default']
    FeatherSun: typeof import('~icons/feather/sun')['default']
    README: typeof import('./components/README.md')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNav: typeof import('./components/TheNav.vue')['default']
  }
}

export { }
